# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
warnings_are_errors: true

cran: http://cran.rstudio.com

os:
  - linux

env:
  global:
  - R_BUILD_ARGS="--no-manual"
  - R_CHECK_ARGS="--as-cran --install-args=--build"
  - WARNINGS_ARE_ERRORS=1

before_install:
  - fname=travis_helpers.sh
  - wget -O ${fname} http://bit.ly/travis_helpers
  - cat ${fname}; source ${fname}; rm ${fname}
  - cat DESCRIPTION
  - export PACKAGE_NAME=`package_name`
  - export RCHECK_DIR=${PACKAGE_NAME}.Rcheck
  - export rundir=$PWD;

script:
  - Rscript -e "devtools::install_github('muschellij2/rnhanesdata', dependencies = TRUE)"
  - cd vignettes && travis_wait 100 Rscript -e "rmarkdown::render('vignette_prediction.Rmd')"
  - cd $rundir